### ISSUE TITLE
如何解决只能搜索前15篇文章的限制？

### ISSUE THREAD

**Issue by haiwx** [itobee/gsearch#2]
需要如何修改 Ghost 配置？ 谢谢。

**Comment by itobee** [comment]
gsearch是通过搜索rss.xml来实现文章搜索的，如果需要搜索所有文章，请检查rss.xml是否包含所有文章

**Comment by LunaYJ** [comment]
https://github.com/LunaYJ/GhostBot 欢迎尝试用我的 方案。。。原来很多方案都是用的 rss来搜索，但是这样的搜索有弊端 就是rss只是最近的15篇，于是我修改了 ghostbot这个搜索引擎的 搜索源，把rss改成了 调用 ghost api 这样就能全文搜索了
